import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
    price: 299.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '2',
    name: 'Minimalist Watch',
    description: 'Elegant and simple watch design that works with any outfit. Water-resistant up to 50m.',
    price: 149.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '3',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact speaker with 360-degree sound and 12-hour battery. Perfect for travel.',
    price: 79.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1589003077984-894e133814c9?w=500&h=500&fit=crop',
    rating: 4.5,
    inStock: true,
  },
  {
    id: '4',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and eco-friendly cotton t-shirt. Available in multiple colors.',
    price: 34.99,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    rating: 4.4,
    inStock: true,
  },
  {
    id: '5',
    name: 'Stainless Steel Water Bottle',
    description: 'Double-insulated water bottle keeps drinks hot or cold for 24 hours. Leak-proof design.',
    price: 44.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1602143407151-7e36dd5f5a0e?w=500&h=500&fit=crop',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '6',
    name: 'Smart Fitness Tracker',
    description: 'Track your steps, heart rate, and sleep patterns. 5-day battery life.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&h=500&fit=crop',
    rating: 4.3,
    inStock: true,
  },
  {
    id: '7',
    name: 'Premium Sunglasses',
    description: 'UV-protected sunglasses with polarized lenses. Stylish design for any occasion.',
    price: 189.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '8',
    name: 'Comfortable Running Shoes',
    description: 'Lightweight and breathable running shoes with superior cushioning and support.',
    price: 119.99,
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    rating: 4.5,
    inStock: true,
  },
  {
    id: '9',
    name: 'Laptop Stand',
    description: 'Adjustable aluminum laptop stand for improved ergonomics and ventilation.',
    price: 59.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1587041537573-42235a4500cf?w=500&h=500&fit=crop',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '10',
    name: 'Wool Winter Beanie',
    description: 'Warm and comfortable beanie made from premium merino wool. One size fits all.',
    price: 39.99,
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1515894550569-0f76aad67eae?w=500&h=500&fit=crop',
    rating: 4.4,
    inStock: true,
  },
  {
    id: '11',
    name: 'Phone Camera Lens Protector',
    description: 'Tempered glass lens protector that keeps your phone camera safe from scratches.',
    price: 14.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1609034227505-5876f6aa4e90?w=500&h=500&fit=crop',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '12',
    name: 'Artisan Coffee Maker',
    description: 'Manual pour-over coffee maker for the perfect cup every time. Includes filters.',
    price: 69.99,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f4?w=500&h=500&fit=crop',
    rating: 4.9,
    inStock: true,
  },
]

export const categories = Array.from(new Set(products.map(p => p.category)))
